name: 'Trabalho Final'

on:
  workflow_dispatch:

jobs:
  testes-unitarios:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x  # LTS estável recomendada

      - name: Instalar Yarn globalmente
        run: npm install -g yarn

      - name: Instalar dependências do projeto
        run: yarn install

      - name: Listar arquivos na pasta de testes
        run: ls -la ./testes  

      - name: Executar testes unitários com Mocha
        run: yarn test
